import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { parse } from 'acorn';
import { format } from 'prettier';

const root = dirname(fileURLToPath(import.meta.url));
const output = resolve(root, '../../ipaverse/ipaverse/Resources/FridaScripts');
const manifest = JSON.parse(await readFile(resolve(root, 'manifest.json'), 'utf8'));
const check = process.argv.includes('--check');
for (const script of manifest.scripts) {
  const source = await readFile(resolve(root, 'src', script.name), 'utf8');
  let runtime = '';
  if (script.runtimeSHA256) {
    runtime = await readFile(resolve(root, 'vendor', script.name), 'utf8');
    if (createHash('sha256').update(runtime).digest('hex') !== script.runtimeSHA256) {
      throw new Error(`${script.name}: frozen bridge checksum changed; review the runtime update explicitly.`);
    }
  }
  const body = await format(source, { parser: 'babel' });
  const generated = '// Generated by tools/frida/build.mjs; edit tools/frida/src instead.\n' +
    (runtime ? `(() => {\n${runtime}\n${body}\n})();\n` : body);
  parse(generated, { ecmaVersion: 'latest', sourceType: 'script' });
  if (script.name === 'class-method-tracer.js' && !generated.includes('{{CLASS_NAME}}')) {
    throw new Error('Class-name placeholder is missing.');
  }
  const path = resolve(output, script.name);
  if (check) {
    if (await readFile(path, 'utf8') !== generated) throw new Error(`${script.name}: run npm run build in tools/frida.`);
  } else {
    await writeFile(path, generated);
  }
  console.log(`${check ? 'Verified' : 'Built'} ${script.name}`);
}
